import fs from "fs";
import path from "path";


const ROOTS = [
    "src/components",
    "src/hooks",
    "src/services",
    "src/types",
    "src/utils",
];


const GENERATED_HEADER =
    "// AUTO-GENERATED BY generate-barrels.js\n";


const IGNORE_DIRS = [
    "node_modules",
    ".git",
    "dist",
    "build",
];


const IGNORE_FILES = [
    "index.ts",
    "index.tsx",
];


const IGNORE_EXTENSIONS = [
    ".css",
    ".scss",
    ".sass",
    ".less",
    ".png",
    ".jpg",
    ".jpeg",
    ".svg",
    ".gif",
    ".webp",
];



function isIgnoredFile(file) {

    if (
        IGNORE_FILES.includes(file)
    ) {
        return true;
    }


    return IGNORE_EXTENSIONS.some(
        ext => file.endsWith(ext)
    );

}



function hasDefaultExport(content) {

    return /export\s+default/.test(content);

}



function isGeneratedFile(file) {

    if (
        !fs.existsSync(file)
    ) {
        return false;
    }


    const content =
        fs.readFileSync(
            file,
            "utf8"
        );


    return content.startsWith(
        GENERATED_HEADER
    );

}



function removeGeneratedIndex(folder) {

    const index =
        path.join(
            folder,
            "index.ts"
        );


    if (
        isGeneratedFile(index)
    ) {

        fs.unlinkSync(index);

        console.log(
            "🗑 removido:",
            index
        );

    }

}




function generateFolder(folder) {


    const entries =
        fs.readdirSync(
            folder,
            {
                withFileTypes:true
            }
        );


    const exports = [];



    /*
        1 - Primeiro procura componentes em pastas

        Ex:
        EventModal/
            index.tsx
    */


    for (
        const entry of entries
    ) {


        if (
            !entry.isDirectory()
        )
        continue;


        if (
            IGNORE_DIRS.includes(
                entry.name
            )
        )
        continue;



        const child =
            path.join(
                folder,
                entry.name
            );



        const childIndex =
            path.join(
                child,
                "index.tsx"
            );



        if (
            fs.existsSync(
                childIndex
            )
        ) {


            exports.push(
                `export { default as ${entry.name} } from "./${entry.name}";`
            );


            continue;

        }



        generateFolder(child);



        const childBarrel =
            path.join(
                child,
                "index.ts"
            );


        if (
            fs.existsSync(childBarrel)
        ) {


            exports.push(
                `export * from "./${entry.name}";`
            );


        }


    }




    /*
        2 - Procura arquivos ts / tsx
    */


    for (
        const entry of entries
    ) {


        if (
            entry.isDirectory()
        )
        continue;



        if (
            isIgnoredFile(
                entry.name
            )
        )
        continue;



        const ext =
            path.extname(
                entry.name
            );



        if (
            ext !== ".ts" &&
            ext !== ".tsx"
        )
        continue;



        const filePath =
            path.join(
                folder,
                entry.name
            );



        const content =
            fs.readFileSync(
                filePath,
                "utf8"
            );



        const name =
            path.basename(
                entry.name,
                ext
            );



        if (
            hasDefaultExport(
                content
            )
        ) {


            exports.push(
                `export { default as ${name} } from "./${name}";`
            );


        }
        else {


            exports.push(
                `export * from "./${name}";`
            );


        }


    }





    /*
        3 - Decide se cria ou remove barrel
    */


    const index =
        path.join(
            folder,
            "index.ts"
        );



    const unique =
        [...new Set(exports)]
        .sort();



    /*
        Menos de 2 exports
        não merece barrel
    */


    if (
        unique.length < 2
    ) {


        removeGeneratedIndex(
            folder
        );


        return;

    }




    /*
        Não cria barrel dentro
        de componente
    */


    if (
        fs.existsSync(
            path.join(
                folder,
                "index.tsx"
            )
        )
    ) {


        removeGeneratedIndex(
            folder
        );


        return;

    }





    const content =
        GENERATED_HEADER +
        "\n" +
        unique.join("\n") +
        "\n";




    fs.writeFileSync(
        index,
        content
    );


    console.log(
        "✓ criado:",
        index
    );

}





for (
    const root of ROOTS
) {


    if (
        fs.existsSync(root)
    ) {


        generateFolder(root);


    }

}



console.log(
    "\n✅ Barrels sincronizados."
);